version: '3.6'

services:

#    http-client-battle:
#      image: bb/workout/http-client-battle
#      build:
#        context: .
#      environment:
#        JAEGER_SERVICE_NAME: http-client-battle

  jaeger:
    image: jaegertracing/all-in-one
    network_mode: bridge
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  prometheus:
    image: prom/prometheus
    network_mode: bridge
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  prometheus-pushgateway:
    image: prom/pushgateway
    network_mode: bridge
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    network_mode: bridge
    restart: always
    ports:
      - 3000:3000
