version: '3.7'

services:

    http-client-battle:

      image: bb/workout/http-client-battle
      network_mode: bridge
      build:
        context: ../
      environment:
        JAEGER_SERVICE_NAME: http-client-battle
        JAEGER_AGENT_HOST: xxx.xxx.xxx.xxx
        MAX_REQUEST_PER_MINUTE: 1000000
        TEST_DURATION_SECONDS: 60
        PROMETHEUS_PUSHGATEWAY: xxx.xxx.xxx.xxx:9091
        URL_SERVER_PROTOCOL: http
        URL_SERVER_DOMAIN: xxx.xxx.xxx.xxx
        URL_SERVER_PORT: 8080
        URL_SERVER_PATH: /hit_me
        URL_SERVER: http://xxx.xxx.xxx.xxx:8080/hit_me
      volumes:
      - ${CLIENT_JAR}:/opt/http-client-battle/client-jar/http-client.jar